### ISSUE TITLE
Feature request: CSV import

### ISSUE THREAD

**Issue by philipaarseth** [fjaros/cleangroupassigns#7]
Hey,

I know plenty of guilds who make their rosters on google sheets. Something that would be a fantastic middle step here would be the ability to import for instance a csv file/ string to automatically create an arrangement.

**Comment by tobbi007** [comment]
Hey, I made a little csv import that works for me. It just needs all 40 players separated by comma with no spaces.
I also sent a Mail to @fjaros so he can integrate it into this repo (I currently do not have github on this machine so i did not create a pull request).

[cleangroupassigns.zip](https://github.com/fjaros/cleangroupassigns/files/6085861/cleangroupassigns.zip)

**Comment by philipaarseth** [comment]
@fjaros

**Comment by philipaarseth** [comment]
@tobbi007 I tested it out a little and it works quite well, well done!
Only problem is that it requires per line trailing comma which I don't think is standard .csv behaviour.
If you export from google sheets for instance, it will give you without trailing comma.
Maybe consider fixing that first?

**Comment by tobbi007** [comment]
@philipaarseth I think it is standard csv behaviour. Its just a table with  one row and 40 columns.
I made it like that because other addons do it the same way (looking at https://www.curseforge.com/wow/addons/raid-group-organizer). In a spreadsheet you can do a formular to get that comma separated line anyway.

But I also don not mind changing it.

**Comment by fjaros** [comment]
thanks so much for doing the work. in general i haven't bothered with it since my guild has no need for it, but i understand it can be really useful for others. I'll take a look at your changes and provide some comments.
the solution should be able to parse the input in a smart way - a number of additional separators like , \t space should be supported. leading/trailing separators should be trimmed.

**Comment by tobbi007** [comment]
Sounds great. I didn't bother looking at other separators and I really do not know lua or the wow api really well 😄 
A friend is organizing a lot of gdkp pugs and I wanted to help him out with that. So I might aswell share.
I thought multiple separators weren't really needed. I think most people will just do the formular once in their sheet and then forget about it.  But a good explanation of the format for sure is needed (I did not do a great job there).

**Comment by fjaros** [comment]
some feedback:
1) the child dialog should be anchored to the parent. this way if you drag the parent to another part of the screen, the import dialog will display in the center of the parent, not in the center of the screen.
2) my first "test" import of "player1,player2,player3" throws a lua error once clicking on the imported roster. it might be because the roster expects exactly 40 players? it should be able to handle any number 1-40

I can help to make the effort production ready but somewhat busy lately so might be a week or two

**Comment by tobbi007** [comment]
Hey,

I made some changes:

1. Subframe will always show on center of parent frame.
2. The import did not expect exactly 40 players. But there was an issue that the players not getting added to the playerTable correctly

Also the function AddToPlayerTable added players with a capital letter to the playertable and the import just added the players to the arrangementsdb "how they were written". So that was a conflict that is fixed now, first letter is always capital.


[cleangroupassigns.zip](https://github.com/fjaros/cleangroupassigns/files/6106851/cleangroupassigns.zip)

**Comment by fjaros** [comment]
awesome. looks good! i'll make some time to merge this in over the weekend

**Comment by fjaros** [comment]
Cleaned up & improved it a bit. Released in https://github.com/fjaros/cleangroupassigns/commit/736029bb45f761eb97685cccae7ac37054115ceb. Thanks for your contribution!
